platform:ios,‘8.0’
use_frameworks!
target  ‘YeeMVVMDemo’  do  
pod   'AFNetworking', '~> 3.1.0'
pod   'MJExtension', '~> 3.0.10'
pod   'SDWebImage', '~> 3.7.5'
pod   'MJRefresh', '~> 3.1.12'
pod   'SDCycleScrollView', '~> 1.64'#轮播器
pod   'Masonry', '~> 1.0.1'
pod   'IQKeyboardManager'#用于键盘管理
pod   'ReactiveObjC', '~> 2.1.0'
end