platform:ios,‘8.0’
use_frameworks!
target  ‘YeeMVVMFrameWork’  do  
pod     'AFNetworking', '~> 3.1.0'
pod    'MJExtension', '~> 3.0.13'
pod    'SDWebImage', '~> 4.0.0'
pod    'MJRefresh', '~> 3.1.12'
pod    'Masonry', '~> 1.0.2'
pod    'IQKeyboardManager'#用于键盘管理
pod    'ReactiveObjC', '~> 3.0.0'
end